<template>
  <v-container class="mt-5 px-5">
    <h1>Privacy policy</h1>
    <p>Last updated: 2022-07-21</p>

    <p class="text-h5 font-weight-bold white--text">Introduction</p>
    <v-card-text class="px-0 text-h6">
      Welcome to Skriptag (“Company”, “we”, “our”, “us”)! As you have just clicked our Terms of Service, please pause, grab a cup
      of coffee and carefully read the following pages. It will take you approximately 20 minutes.
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      Our Privacy Policy governs your visit to skriptag.com, and explains how we collect, safeguard and disclose information that
      results from your use of our Service.
    </v-card-text>

    <v-card-text class="px-0 text-h6">
      We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in
      accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the
      same meanings as in our Terms and Conditions.
    </v-card-text>

    <v-card-text class="px-0 text-h6">
      Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your
      agreement with us (“agreement”).
    </v-card-text>

    <p class="text-h5 font-weight-bold mt-5 white--text">Definitions</p>
    <v-card-text class="px-0 text-h6"> SERVICE means Skriptag's website operated by Skriptag. </v-card-text>
    <v-card-text class="px-0 text-h6">
      PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other
      information either in our possession or likely to come into our possession).
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for
      example, the duration of a page visit).
    </v-card-text>
    <v-card-text class="px-0 text-h6"> COOKIES are small files stored on your device (computer or mobile device). </v-card-text>
    <v-card-text class="px-0 text-h6">
      DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the
      purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy
      Policy, we are a Data Controller of your data.
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data
      Controller. We may use the services of various Service Providers in order to process your data more effectively.
    </v-card-text>
    <v-card-text class="px-0 text-h6"> DATA SUBJECT is any living individual who is the subject of Personal Data. </v-card-text>
    <v-card-text class="px-0 text-h6">
      THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
    </v-card-text>
    <p class="text-h5 font-weight-bold mt-5 white--text">Information Collection and Use</p>
    <v-card-text class="px-0 text-h6">
      We collect several different types of information for various purposes to provide and improve our Service to you.
    </v-card-text>
    <p class="text-h5 font-weight-bold mt-5 white--text">Types of Data Collected</p>
    <p class="text-h6 font-weight-bold mt-2 mb-n2">Personal Data</p>
    <v-card-text class="px-0 text-h6">
      While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to
      contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
    </v-card-text>
    <v-card-text class="px-0 text-h6"> (a) Email address </v-card-text>
    <v-card-text class="px-0 text-h6">
      We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that
      may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the
      unsubscribe link.
    </v-card-text>
    <p class="text-h6 font-weight-bold mt-2 mb-n2">Usage data</p>
    <v-card-text class="px-0 text-h6">
      We may also collect information that your browser sends whenever you visit our Service or when you access Service by or
      through a mobile device (“Usage Data”).
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type,
      browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages,
      unique device identifiers and other diagnostic data.
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you
      use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile
      Internet browser you use, unique device identifiers and other diagnostic data.
    </v-card-text>
    <v-card-text class="px-0 text-h6"> Tracking Cookies Data </v-card-text>
    <v-card-text class="px-0 text-h6">
      We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your
      browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and
      scripts to collect and track information and to improve and analyze our Service.
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not
      accept cookies, you may not be able to use some portions of our Service.
    </v-card-text>
    <v-card-text class="px-0 text-h6"> Examples of Cookies we use: </v-card-text>
    <v-card-text class="px-0 text-h6"> (a) Session Cookies: We use Session Cookies to operate our Service. </v-card-text>
    <v-card-text class="px-0 text-h6">
      (b) Preference Cookies: We use Preference Cookies to remember your preferences and various settings.
    </v-card-text>
    <v-card-text class="px-0 text-h6"> (c) Security Cookies: We use Security Cookies for security purposes. </v-card-text>
    <v-card-text class="px-0 text-h6">
      (d) Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your
      interests.
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      (e) to gather analysis or valuable information so that we can improve our Service;
    </v-card-text>
    <v-card-text class="px-0 text-h6">
      (e) to gather analysis or valuable information so that we can improve our Service;
    </v-card-text>
    <v-card-text class="px-0 text-h6"> (f) to monitor the usage of our Service; </v-card-text>
    <v-card-text class="px-0 text-h6"> (g) to detect, prevent and address technical issues; </v-card-text>
    <v-card-text class="px-0 text-h6"> (h) to fulfill any other purpose for which you provide it; </v-card-text>
    <v-card-text class="px-0 text-h6">
      (i) to carry out our obligations and enforce our rights arising from any contracts entered into between you and us,
      including for billing and collection;</v-card-text
    >
    <v-card-text class="px-0 text-h6">
      (j) to provide you with notices about your account and/or subscription, including expiration and renewal notices,
      email-instructions, etc.;
    </v-card-text>

    <v-card-text class="px-0 text-h6">
      (k) to provide you with news, special offers and general information about other goods, services and events which we offer
      that are similar to those that you have already purchased or enquired about unless you have opted not to receive such
      information;
    </v-card-text>

        <v-card-text class="px-0 text-h6">
      (k) to provide you with news, special offers and general information about other goods, services and events which we offer
      that are similar to those that you have already purchased or enquired about unless you have opted not to receive such
      information;
    </v-card-text>
    
  </v-container>
</template>
<script>
  export default {
    name: 'Homepage',
  };
</script>
